### ISSUE TITLE
Indicating things are paid/not paid

### ISSUE THREAD

**Issue by lethargilistic** [progdisc/resources#13]
With the AwesomeBot dump from #10, we now have resources with, let's say, legacy names. Do we really need to identify things as paid/unpaid as a part of the title? I've seen other Awesome lists that used emoji to indicate things about each resource. What if, instead of saying "Paid," we used :moneybag:, :dollar:, :heavy_dollar_sign: to indicate that a resource costs money?

Following that, what would be a good symbol for free? :sparkles:?

We could take this as far as we want to, really. :book: for book, :movie_camera: for video, :studio_microphone: for sound?

**Comment by rgoliveira** [comment]
Love this idea! Way more visual, easier to spot what you want.

I propose the following to get this discussion going (please comment/suggest about them before we settle):

| Property      | Emoji |
| ------------- | --- |
| Paid  | :heavy_dollar_sign: |
| Free | :free: (no idea what would be better... maybe :rainbow:?) |
| Book  | :books: |
| Document (e.g. cheat sheet, white paper, ...) | :page_facing_up: |
| Video | :movie_camera: |
| Podcast/audio | :studio_microphone: |
| Documentation/manual | :blue_book: |
| Course | :mortar_board: |
| Tutorial | :footprints: |
| Newsletter/subscription stuff | :mailbox: |
| Assorted link | :globe_with_meridians: |

Did I miss something? I tried to skim through what we already have and pick an emoji.

**Comment by lethargilistic** [comment]
I like this, but I don't think we should have that many. After all, if there are so many to pick from, it would be difficult for someone to understand at a glance without looking at the key.

| Property      | Emoji | Comment |
| ------------- | --- | -----------|
| Paid  | :heavy_dollar_sign: | Yes
| Free | :free::rainbow::sparkles: | I don't like :free: because it's not really visual, but it would be clear without the key.
| Video | :movie_camera: | Yes
| Podcast/audio | :studio_microphone: | Yes
| Book/Documents | :blue_book::orange_book::green_book: | Merge Documentation, Book, manuals
| Course/Tutorial | :mortar_board: | Merged Course, Tutorial
| Newsletter/subscription stuff | :mailbox: | Hesitant yes. I feel like this would be a document, but it's a significantly different experience. Could also include blogs.
| Assorted link | :globe_with_meridians: | I guess this would take up space and align all the items, but I'm not sure it's necessary

And, since everything would either be paid or free, we could combine them like so: :sparkles::movie_camera:, :heavy_dollar_sign::book:

**Comment by micwill007** [comment]
Looks like a solid legend. 

I like <g-emoji alias="free" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f193.png" ios-version="6.0">🆓</g-emoji> - universal and simple. 

How about courses that offer a certificate of completion or similar? 📇

**Comment by lethargilistic** [comment]
I guess that's me outvoted on :free:. ^^

I don't think that offering a certificate would be a useful distinction here. If we go with the mixing idea (:free::movie_camera:), then some of them would have three emoji and others would have two, as well.

**Comment by micwill007** [comment]
No problem - scratch the certificate symbol.

+1 for the mixing idea from me 😄.

**Comment by rgoliveira** [comment]
Yeah, mixing is the way to go. Just paste the ones that apply.

I've just merged the remaining PRs, so now is a good time to deal with this.

If anyone want to review each link and add the emojis, I guess just say something here so everyone knows it's being done. (Maybe even open a WIP PR to make it even more clear.)

**Comment by Heasummn** [comment]
I have added the emoji to every link, in #23. I will merge it if everyone thinks it's okay, however, I feel like using an emoji to symbolize something is free is not the way to go. Using a paid emoji would be much nicer.

**Comment by lethargilistic** [comment]
Well, the idea we've been developing includes both a free and a paid emoji, so I feel like we've already agreed and compromised. XD
