### ISSUE TITLE
Github Pages?

### ISSUE THREAD

**Issue by maxwenger** [progdisc/resources#2]
Lets setup Github pages and pick a pretty theme!

**Comment by Heasummn** [comment]
Using Jekyll, we can easily move our current layout to Github Pages. I like this idea and second it.

**Comment by rgoliveira** [comment]
That's what I had in mind from the beginning, but some argued it was too much of an overhead to deal with Jekyll and people would end up holding back on contributions.

I think it's a great idea and much better than than just a giant README file.

**Comment by rgoliveira** [comment]
Ok, people (@progdisc/sourcers), I've setup the basic Jekyll thingy on the repo.

Link: https://progdisc.github.io/resources/

I didn't really like any of the themes, but suggestions are welcome.

**Comment by tbodt** [comment]
Dealing with jekyll isn't any harder than dealing with a lot of markdown files, since jekyll works on a lot of markdown files.

About the theme, why don't we make our own?

**Comment by Heasummn** [comment]
If we use Github pages, I feel like seperating across multiple pages might be a bit nicer. The current format does not bode well with pages.

**Comment by lethargilistic** [comment]
I don't think this would be a problem. There are many awesome-lists:tm: that are extremely long. What about Github Pages, which is a secondary view, would make keeping this one page difficult to deal with?

**Comment by rgoliveira** [comment]
Just leaving this here for future reference: [GH pages can now use any Jekyll theme out there](https://blog.github.com/2017-11-29-use-any-theme-with-github-pages/).

**Comment by tbodt** [comment]
Not that you couldn't already use any Jekyll theme out there, by copying it into your repo.
