### ISSUE TITLE
The current Github pages theme gets rid of the # in C#

### ISSUE THREAD

**Issue by LaVieEstDure** [progdisc/resources#22]
![image](https://user-images.githubusercontent.com/28722943/31856391-4f48eb9c-b703-11e7-948b-3401857d48b2.png)

**Comment by rgoliveira** [comment]
Nice catch.
Maybe it's something to do with how you can make titles in markdown like `### title ###`, so it's stripping trailing #'s.

Can anyone check if that's the case and see how to escape that #?

**Comment by ecoerod** [comment]
Fixed in the latest commit. Closed.
