### ISSUE TITLE
We need a solid format for new sections

### ISSUE THREAD

**Issue by lethargilistic** [progdisc/resources#6]
We're adding whatever we want, however we want, and that's cool for right now, but what about long-term? I think we should solidify a template for a section. I like the following:

## Subject
*Description*
### Learning
* Thing1 - Short description of Thing 1
* Thing2 - Short description of Thing 2
### Culture
* Thing3 - Short description of Thing 3

**Comment by palatano** [comment]
Sure, I was aiming for something like that with the Java section. What should we consider as culture topics, so that we don't add too many under the category?

**Comment by Heasummn** [comment]
I think it would be better to make Learning and Culture their own category like "Languages" is right now. We could then split those by language.

**Comment by seekheart** [comment]
Not sure if this goes here but should we have a format for Submitting PRs and proposals?

**Comment by rgoliveira** [comment]
Not sure what you mean, @seekheart, but I think it's better to keep this issue about the format of the contents.

And about @Heasummn proposal: I don't like the idea of making 'learning' and 'culture' their own categories. We would need to split them by language anyways, right?

**Comment by lethargilistic** [comment]
@palatano I don't think having a hard limit on the amount of them in a section is necessary. If one gets seriously bloated, I like to think we'll consider cutting it down together.

**Comment by lethargilistic** [comment]
I have added the suggestion to the repo, under contribution guidelines, to get this going. If there are no other concerns to address right now, we can close the issue and edit the list to follow it.

**Comment by GrahamCorcoran** [comment]
@lethargilistic Are you doing away with Materials? I feel like Materials bridges the gap between learning and culture well, but perhaps three subheadings is too many?

**Comment by lethargilistic** [comment]
@Grambles We never really discussed what distinguishes Materials from the other two, so, as far as I know, it's just Learning. It's true that I'm resistant to a third category, but what would you say is the concrete difference?
